*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jul 12 00:24:20 2021] ***
compiled with version: 9.3.0 on 11 July 2021 16:14:03
os: Linux-5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021
nodename: fx-VirtualBox
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/fx/develop/py/github/django_test/proj1
writing pidfile to uwsgi.pid
detected binary path: /home/fx/develop/py/github/django_test/proj1/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/fx/develop/py/github/django_test/proj1
your processes number limit is 7719
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:45613 (port auto-assigned) fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
Python main interpreter initialized at 0x5639284d4bc0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166688 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "proj1/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fx/develop/py/github/django_test/proj1/./proj1/settings.py", line 28
    ALLOWED_HOSTS = [*]
                      ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7273)
spawned uWSGI worker 1 (pid: 7276, cores: 2)
spawned uWSGI http 1 (pid: 7277)
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jul 12 00:24:39 2021] ***
compiled with version: 9.3.0 on 11 July 2021 16:14:03
os: Linux-5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021
nodename: fx-VirtualBox
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/fx/develop/py/github/django_test/proj1
writing pidfile to uwsgi.pid
detected binary path: /home/fx/develop/py/github/django_test/proj1/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/fx/develop/py/github/django_test/proj1
your processes number limit is 7719
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8000).
bind(): Address already in use [core/socket.c line 769]
Mon Jul 12 00:27:01 2021 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Jul 12 00:27:01 2021 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jul 12 00:31:18 2021] ***
compiled with version: 9.3.0 on 11 July 2021 16:14:03
os: Linux-5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021
nodename: fx-VirtualBox
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/fx/develop/py/github/django_test/proj1
writing pidfile to uwsgi.pid
detected binary path: /home/fx/develop/py/github/django_test/proj1/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/fx/develop/py/github/django_test/proj1
your processes number limit is 7719
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
Python main interpreter initialized at 0x56239e29fad0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166688 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "proj1/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fx/develop/py/github/django_test/proj1/./proj1/settings.py", line 28
    ALLOWED_HOSTS = [*]
                      ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7433)
spawned uWSGI worker 1 (pid: 7436, cores: 2)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
--- no python application found, check your startup logs for errors ---
[pid: 7436|app: -1|req: -1/1] 127.0.0.1 () {40 vars in 608 bytes} [Mon Jul 12 00:31:54 2021] GET /v1/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7436|app: -1|req: -1/2] 127.0.0.1 () {38 vars in 529 bytes} [Mon Jul 12 00:31:54 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7436|app: -1|req: -1/3] 127.0.0.1 () {40 vars in 612 bytes} [Mon Jul 12 00:32:25 2021] GET /admin => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7436|app: -1|req: -1/4] 127.0.0.1 () {38 vars in 529 bytes} [Mon Jul 12 00:32:25 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7436|app: -1|req: -1/5] 127.0.0.1 () {40 vars in 606 bytes} [Mon Jul 12 00:32:31 2021] GET /v1 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7436|app: -1|req: -1/6] 127.0.0.1 () {38 vars in 529 bytes} [Mon Jul 12 00:32:31 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jul 12 00:35:35 2021] ***
compiled with version: 9.3.0 on 11 July 2021 16:14:03
os: Linux-5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021
nodename: fx-VirtualBox
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/fx/develop/py/github/django_test/proj1
writing pidfile to uwsgi.pid
detected binary path: /home/fx/develop/py/github/django_test/proj1/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/fx/develop/py/github/django_test/proj1
your processes number limit is 7719
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
Python main interpreter initialized at 0x55b7b080fad0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166688 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "proj1/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fx/develop/py/github/django_test/proj1/./proj1/settings.py", line 28
    ALLOWED_HOSTS = [*,]
                      ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7555)
spawned uWSGI worker 1 (pid: 7558, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 7558|app: -1|req: -1/1] 127.0.0.1 () {40 vars in 606 bytes} [Mon Jul 12 00:35:45 2021] GET /v1 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7558|app: -1|req: -1/2] 127.0.0.1 () {38 vars in 529 bytes} [Mon Jul 12 00:35:45 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7558|app: -1|req: -1/3] 127.0.0.1 () {40 vars in 606 bytes} [Mon Jul 12 00:35:47 2021] GET /v1 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7558|app: -1|req: -1/4] 127.0.0.1 () {40 vars in 606 bytes} [Mon Jul 12 00:36:15 2021] GET /v1 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
--- no python application found, check your startup logs for errors ---
[pid: 7558|app: -1|req: -1/5] 127.0.0.1 () {40 vars in 602 bytes} [Mon Jul 12 00:36:29 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7558|app: -1|req: -1/6] 127.0.0.1 () {40 vars in 606 bytes} [Mon Jul 12 00:36:33 2021] GET /v1 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jul 12 00:37:52 2021] ***
compiled with version: 9.3.0 on 11 July 2021 16:14:03
os: Linux-5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021
nodename: fx-VirtualBox
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/fx/develop/py/github/django_test/proj1
writing pidfile to uwsgi.pid
detected binary path: /home/fx/develop/py/github/django_test/proj1/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/fx/develop/py/github/django_test/proj1
your processes number limit is 7719
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
Python main interpreter initialized at 0x55bdd8a02ad0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166688 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
Traceback (most recent call last):
  File "proj1/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fx/develop/py/github/django_test/proj1/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fx/develop/py/github/django_test/proj1/./proj1/settings.py", line 28
    ALLOWED_HOSTS = [*,]
                      ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7625)
spawned uWSGI worker 1 (pid: 7628, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 7628|app: -1|req: -1/1] 127.0.0.1 () {42 vars in 637 bytes} [Mon Jul 12 00:37:56 2021] GET /v1 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7628|app: -1|req: -1/2] 127.0.0.1 () {42 vars in 637 bytes} [Mon Jul 12 00:37:57 2021] GET /v1 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7628|app: -1|req: -1/3] 127.0.0.1 () {42 vars in 637 bytes} [Mon Jul 12 00:38:43 2021] GET /v1 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7628|app: -1|req: -1/4] 127.0.0.1 () {40 vars in 606 bytes} [Mon Jul 12 00:38:45 2021] GET /v1 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 7628|app: -1|req: -1/5] 127.0.0.1 () {42 vars in 637 bytes} [Mon Jul 12 00:45:56 2021] GET /v1 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jul 12 00:46:09 2021] ***
compiled with version: 9.3.0 on 11 July 2021 16:14:03
os: Linux-5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021
nodename: fx-VirtualBox
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/fx/develop/py/github/django_test/proj1
writing pidfile to uwsgi.pid
detected binary path: /home/fx/develop/py/github/django_test/proj1/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/fx/develop/py/github/django_test/proj1
your processes number limit is 7719
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
Python main interpreter initialized at 0x55aec450ead0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166688 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55aec450ead0 pid: 8076 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8076)
spawned uWSGI worker 1 (pid: 8078, cores: 2)
***************** app1.views.py init do something **************************
***************** app1.urls.py init do something **************************
***************** proj1.urls.py init do something **************************
[pid: 8078|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 637 bytes} [Sun Jul 11 16:46:13 2021] GET /v1 => generated 0 bytes in 23 msecs (HTTP/1.1 301) 5 headers in 172 bytes (1 switches on core 0)
xxxxxx 2
127.0.0.1
[pid: 8078|app: 0|req: 2/2] 127.0.0.1 () {42 vars in 639 bytes} [Sun Jul 11 16:46:13 2021] GET /v1/ => generated 14 bytes in 12 msecs (HTTP/1.1 200) 5 headers in 165 bytes (1 switches on core 1)
xxxxxx 3
127.0.0.1
[pid: 8078|app: 0|req: 3/3] 127.0.0.1 () {42 vars in 639 bytes} [Sun Jul 11 16:46:14 2021] GET /v1/ => generated 14 bytes in 0 msecs (HTTP/1.1 200) 5 headers in 165 bytes (1 switches on core 0)
